// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIqVjQ_hqcO0JJX80fWqB6d75t3IPbDg',
    appId: '1:156720314553:web:d49a850427f6de241c0368',
    messagingSenderId: '156720314553',
    projectId: 'zakz-app',
    authDomain: 'zakz-app.firebaseapp.com',
    storageBucket: 'zakz-app.appspot.com',
    measurementId: 'G-73ZK45KX2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyMrA6qZOTSKYWs6n4pV2XZE--AuWRSo',
    appId: '1:156720314553:android:9d505b59f78afb291c0368',
    messagingSenderId: '156720314553',
    projectId: 'zakz-app',
    storageBucket: 'zakz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHnH4HdwtpY4LPOuoqVix3yEaVuGhd5Y',
    appId: '1:156720314553:ios:db31ab3dcfbf652f1c0368',
    messagingSenderId: '156720314553',
    projectId: 'zakz-app',
    storageBucket: 'zakz-app.appspot.com',
    iosBundleId: 'com.tranquillodev.zakz.zakz',
  );
}
