name: main push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze > analyze_logs.txt
      - run: dart analyze . >> analyze_logs.txt
      - name: Check for analysis issues
        run: |
          if [[ $(cat analyze_logs.txt | grep -c "error") -gt 0 ]]; then
            echo "Analysis found critical errors. Failing the build."
            exit 1
          fi
      - run: flutter build apk --release
